#!/usr/bin/env bash

# Creates all 1 store types via the Keyfactor Command REST API using curl.
#
# Authentication (first matching method is used):
#   OAuth access token:   KEYFACTOR_AUTH_ACCESS_TOKEN
#   OAuth client creds:   KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET
#                         + KEYFACTOR_AUTH_TOKEN_URL
#   Basic auth (AD):      KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN
#
# Always required:
#   KEYFACTOR_HOSTNAME    Command hostname (e.g. my-command.example.com)
#
# Auto-generated by doctool generate-store-type-scripts — do not edit by hand.

if [ -z "${KEYFACTOR_HOSTNAME}" ]; then
    echo "ERROR: KEYFACTOR_HOSTNAME is required"
    exit 1
fi

BASE_URL="https://${KEYFACTOR_HOSTNAME}/keyfactorapi"

# ---------------------------------------------------------------------------
# Resolve auth
# ---------------------------------------------------------------------------
if [ -n "${KEYFACTOR_AUTH_ACCESS_TOKEN}" ]; then
    BEARER_TOKEN="${KEYFACTOR_AUTH_ACCESS_TOKEN}"
elif [ -n "${KEYFACTOR_AUTH_CLIENT_ID}" ] && [ -n "${KEYFACTOR_AUTH_CLIENT_SECRET}" ] && [ -n "${KEYFACTOR_AUTH_TOKEN_URL}" ]; then
    echo "Fetching OAuth token..."
    BEARER_TOKEN=$(curl -s -X POST "${KEYFACTOR_AUTH_TOKEN_URL}" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        --data-urlencode "grant_type=client_credentials" \
        --data-urlencode "client_id=${KEYFACTOR_AUTH_CLIENT_ID}" \
        --data-urlencode "client_secret=${KEYFACTOR_AUTH_CLIENT_SECRET}" | jq -r '.access_token')
    if [ -z "${BEARER_TOKEN}" ] || [ "${BEARER_TOKEN}" = "null" ]; then
        echo "ERROR: Failed to fetch OAuth token from ${KEYFACTOR_AUTH_TOKEN_URL}"
        exit 1
    fi
elif [ -n "${KEYFACTOR_USERNAME}" ] && [ -n "${KEYFACTOR_PASSWORD}" ] && [ -n "${KEYFACTOR_DOMAIN}" ]; then
    BEARER_TOKEN=""
else
    echo "ERROR: Authentication required. Set one of:"
    echo "  KEYFACTOR_AUTH_ACCESS_TOKEN"
    echo "  KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET + KEYFACTOR_AUTH_TOKEN_URL"
    echo "  KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN"
    exit 1
fi

if [ -n "${BEARER_TOKEN}" ]; then
    CURL_AUTH=("-H" "Authorization: Bearer ${BEARER_TOKEN}")
else
    CURL_AUTH=("-u" "${KEYFACTOR_USERNAME}@${KEYFACTOR_DOMAIN}:${KEYFACTOR_PASSWORD}")
fi

create_store_type() {
    local name="$1"
    local body="$2"
    echo "Creating ${name} store type..."
    response=$(curl -s -o /dev/null -w "%{http_code}" \
        -X POST "${BASE_URL}/certificatestoretypes" \
        -H "Content-Type: application/json" \
        -H "x-keyfactor-requested-with: APIClient" \
        "${CURL_AUTH[@]}" \
        -d "${body}")
    if [ "$response" = "200" ] || [ "$response" = "201" ]; then
        echo "  OK (HTTP ${response})"
    else
        echo "  FAILED (HTTP ${response})"
    fi
}

# ---------------------------------------------------------------------------
# CitrixAdc — The DNS or IP Address of the Citrix ADC Appliance.
# ---------------------------------------------------------------------------
create_store_type "CitrixAdc" '{
  "Name": "CitrixAdc",
  "ShortName": "CitrixAdc",
  "Capability": "CitrixAdc",
  "ServerRequired": true,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "PowerShell": false,
  "PrivateKeyAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": true,
    "Remove": true
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": true,
    "StorePassword": {
      "Description": "Enter a password that matches your Citrix validation rules to encrypt private keys when adding/replacing certificates.  Select 'No Value' if you desire an unencrypted private key to be uploaded.",
      "IsPAMEligible": true
    }
  },
  "Properties": [
    {
      "Name": "linkToIssuer",
      "DisplayName": "Link To Issuer",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "timeout",
      "DisplayName": "Login Timeout in seconds",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "3600",
      "Required": false
    }
  ],
  "EntryParameters": [
    {
      "Name": "virtualServerName",
      "DisplayName": "Virtual Server Name",
      "Type": "String",
      "Description": "When adding a certificate, this can be a single VServer name or a comma separated list of VServers to bind to  Note: must match the number of Virtual SNI Cert values.",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      }
    },
    {
      "Name": "sniCert",
      "DisplayName": "SNI Cert",
      "Type": "String",
      "Description": "When adding a certificate, this can be a single boolean value (true/false) or a comma separated list of boolean values to determine whether the binding should use server name indication.  Note: must match the number of Virtual Server Name values.",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      }
    }
  ],
  "StorePathDescription": "The path where certificate files are located on the Citrix ADC appliance.  This value will likely be /nsconfig/ssl/"
}'


echo "Completed."
